### ISSUE TITLE
Rename AdminLocation

### ISSUE THREAD

**Issue by schtauffen** [topiary-io/topiary#16]
I propose we add all topiary-specific variables to a new section of the config, as opposed to how it is currently (root of config.toml). I would also like to rename `AdminLocation` to `adminRoot`, and remove the trailing slash from the root:

``` toml
AdminLocation = "/my-admin/"
```

->

``` toml
[topiary]
  adminRoot = "/my-admin"
```

Let me know if you disagree, or would like to structure the variables differently.

**Comment by doesntgolf** [comment]
Agreed, we should have topiary configuration under `[topiary]`. The one hesitation I've had about adminlocation, though, is there are two possible meanings of our adminlocation/adminroot: the location for the admin on the FE, and the location of the admin templates in the input. In [Hugo's configuration](http://gohugo.io/overview/configuration/), they use contentdir/staticdir/layoutdir/etc. to describe the input locations. Should we have the location of the admin templates use `admindir`, and have `adminroot` describe the admin's FE location?

EDIT: Sorry, didn't mean to close this :)

**Comment by schtauffen** [comment]
I think that would make a lot of sense and agree we should separate the current `AdminLocation` into `admindir` and `adminroot`. I'm a little confused about Hugo's conventions when it comes to slashes, though. For the 'dirs they are not using slashes at all (source: http://gohugo.io/overview/configuration/):

``` toml
contentdir = "content"
```

But for paths they use both leading and trailing slashes:

``` toml
baseurl = "http://yoursite.example.com/"
post = "/:year/:month/:title/"
```

->

``` toml
baseurl = "http://yoursite.example.com"
post = "/:year/:month/:title"
```

In my opinion there is little reason to use trailing slashes.
However, we should probably use  "path" which takes care of standardization. It seems to follow the same convention I am used to, at least in regards to dropping the trailing slash:

https://play.golang.org/p/hvS6ehifMx
https://golang.org/pkg/path/#Join
